
[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "~1.5.0"

